# Usa a imagem oficial do PHP com Laravel
FROM php:8.2-fpm

# Instala dependências
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Instala Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copia o projeto para o container
WORKDIR /var/www
COPY . .

# Instala as dependências do Laravel
RUN composer install

# Permissões para o Laravel
RUN set -ex; \
    mkdir -p /var/www/storage/logs; \
    mkdir -p /var/www/bootstrap/cache; \
    chown -R www-data:www-data /var/www/storage; \
    chown -R www-data:www-data /var/www/bootstrap/cache; \
    chmod -R 775 /var/www/storage; \
    chmod -R 775 /var/www/bootstrap/cache; \
    [ -d /var/www/storage/logs ] || mkdir -p /var/www/storage/logs; \
    [ -d /var/www/bootstrap/cache ] || mkdir -p /var/www/bootstrap/cache; \
    touch /var/www/storage/logs/laravel.log; \
    chown www-data:www-data /var/www/storage/logs/laravel.log

# Expõe a porta 9000 (PHP-FPM)
EXPOSE 9000

# Comando para rodar o Laravel (ajuste se usar Octane, etc.)
CMD ["php-fpm"]