version: '3.8'

services:
  # Serviço Laravel (Products)
  products-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: products-app
    volumes:
      - .:/var/www
    environment:
      - DB_HOST=products-db
      - REDIS_HOST=products-redis

  # Banco de Dados MySQL
  products-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ecommerce_products
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - products-mysql-data:/var/lib/mysql

  # Redis
  products-redis:
    image: redis:alpine

  # Nginx
  products-web:
    image: nginx:alpine
    ports:
      - "8001:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  products-mysql-data: